import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import localFont from 'next/font/local'
import Navbar from './components/layouts/Navbar'
import TopBar from './components/layouts/TopBar'
import { TooltipProvider } from "./components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const euclidCircularB = localFont({
  src: [
    {
      path: './fonts/EuclidCircularB-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/EuclidCircularB-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/EuclidCircularB-Bold.ttf',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-euclid'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${euclidCircularB.className} bg-bookly-bg`}
      >
        <TooltipProvider>
          <div className="flex h-screen bg-bookly-cream">
            <Navbar />
            <div className="flex-1 flex flex-col p-8">
              <TopBar />
              <main className="flex-1 p-8 bg-white rounded-3xl overflow-hidden">
                {children}
              </main>
            </div>
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
